# Site settings
title: Karina Yap
subtitle: 
email: 
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 
exclude: 
  - archive

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/karinayap
# gitlab_url: 
# googleplus_url: 
# instagram_url: 
linkedin_url: https://www.linkedin.com/in/karina-yap/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
